
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include "EventEmitters.h"
#include "Props.h"
#include "States.h"
#include <react/renderer/components/textinput/BaseTextInputShadowNode.h>
#include <react/renderer/components/textinput/TextInputState.h>

namespace facebook::react {

JSI_EXPORT extern const char PasteTextInputComponentName[];

/*
 * `ShadowNode` for <PasteTextInput> component.
 */
class PasteTextInputShadowNode final : public BaseTextInputShadowNode<
                                           PasteTextInputComponentName,
                                           PasteTextInputProps,
                                           PasteTextInputEventEmitter,
                                           TextInputState> {
 public:
  using BaseTextInputShadowNode::BaseTextInputShadowNode;
};

} // namespace facebook::react
